analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.8019978879019618
color:
  saturation: 0.7765958
  brandStrength: 0.9114607430528849
  rhythmicContrast: 0.4553191
  brandColors:
    - '#FFFFFF'
    - '#C02034'
    - '#202F66'
    - '#707070'
    - '#0E8AD0'
  lightness: 0.3744681
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Bluegrassarcheryacademy
typography_spectrum: 0.7596432389691472
