name: Bluegrassarcheryacademy
favicon: null
layout_spectrum: 0.8019978879019618
typography_spectrum: 0.7596432389691472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9114607430528849
  lightness: 0.19698824896477163
  saturation: 0.5912553779780865
  rhythmicContrast: 0.9215587005019188
purpose: []
