analytics:
  twitter: null
  google: null
  facebook: null
name: Bluegrassarcheryacademy
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
typography_spectrum: 0.7596432389691472
color:
  saturation: 0.7765958
  brandStrength: 0.9114607430528849
  lightness: 0.5531915
  brandColors:
    - '#FFFFFF'
    - '#C02034'
    - '#202F66'
    - '#707070'
    - '#0E8AD0'
  rhythmicContrast: 0.6723405
layout_spectrum: 0.5085106
cta:
  bucket: null
  version: null
  domain: null
favicon: null
